from exceptions.api_exception import CustomValidationError


class ObjectExistException(CustomValidationError):
    'object'